/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package primerproyecto.interfaz;

import javax.swing.*;
import primerproyecto.model.Pasajero;

/**
 *
 * @author User
 */
public class GUIEditarPasajero extends javax.swing.JFrame {

    /**
     * Creates new form GUIEditarPasajero
     */
    private Pasajero pasajero;
    private JTextField txtNombre;
    private JTextField txtEdad;
    private Runnable onSaveCallback;
    
    public GUIEditarPasajero() {
        initComponents();
    }

    public GUIEditarPasajero(Pasajero pasajero, Runnable onSaveCallback) {
        this.pasajero = pasajero;
        this.onSaveCallback = onSaveCallback;
        initComponentsK(); // inicializa los componentes

        // Cargar valores actuales del pasajero
        txtNombre.setText(pasajero.getNombre());
        txtEdad.setText(String.valueOf(pasajero.getEdad()));
    }

    @SuppressWarnings("unchecked")
    private void initComponentsK() {

        setTitle("Editar Pasajero");
        setSize(300, 200);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPanel panel = new JPanel();
        panel.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        panel.add(new JLabel("Nombre:"));
        txtNombre = new JTextField();
        panel.add(txtNombre);

        panel.add(new JLabel("Edad:"));
        txtEdad = new JTextField();
        panel.add(txtEdad);

        JButton btnGuardar = new JButton("Guardar");
        btnGuardar.addActionListener(e -> {
            pasajero.setNombre(txtNombre.getText());
            try {
                pasajero.setEdad(Integer.parseInt(txtEdad.getText()));
                JOptionPane.showMessageDialog(this, "Pasajero actualizado correctamente");
                if (onSaveCallback != null) {
                    onSaveCallback.run(); // refresca tabla
                }
                dispose();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Edad inválida");
            }
        });

        JButton btnCancelar = new JButton("Cancelar");
        btnCancelar.addActionListener(e -> dispose());

        panel.add(btnGuardar);
        panel.add(btnCancelar);

        add(panel);
    }
/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Pasajero dummy = new Pasajero("Juan", 25);
        java.awt.EventQueue.invokeLater(() -> {
            new GUIEditarPasajero(dummy, null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
