/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package primerproyecto.interfaz;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import primerproyecto.service.ServicioVehiculo;

/**
 *
 * @author Sebastian
 */
public class GUIPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    private ServicioVehiculo barbosa = ServicioVehiculo.getInstance();

    public GUIPrincipal() {
        this.setTitle("Concesionario AAA");
        setLocationRelativeTo(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        mostrarTarifa = new javax.swing.JMenuItem();
        search = new javax.swing.JMenu();
        addCarro = new javax.swing.JMenuItem();
        updateCarro = new javax.swing.JMenuItem();
        deleteCarro = new javax.swing.JMenuItem();
        listarCarro = new javax.swing.JMenuItem();
        jMenuSearchCarro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        addBus = new javax.swing.JMenuItem();
        updateBus = new javax.swing.JMenuItem();
        deleteBus = new javax.swing.JMenuItem();
        listarBus = new javax.swing.JMenuItem();
        jMenuSearchBus = new javax.swing.JMenuItem();
        jMAddpasajero = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMUpdpasa = new javax.swing.JMenuItem();
        jMDelePasa = new javax.swing.JMenuItem();
        jMListPasajero = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ConcesionarioApp");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/primerproyecto/interfaz/image.png"))); // NOI18N

        archivo.setText("Archivo");

        mostrarTarifa.setText("mostrarTarifa");
        mostrarTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTarifaActionPerformed(evt);
            }
        });
        archivo.add(mostrarTarifa);

        jMenuBar1.add(archivo);

        search.setText("Carro");

        addCarro.setText("Add carro");
        addCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarroActionPerformed(evt);
            }
        });
        search.add(addCarro);

        updateCarro.setText("Update carro");
        updateCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCarroActionPerformed(evt);
            }
        });
        search.add(updateCarro);

        deleteCarro.setText("Delete Carro");
        deleteCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCarroActionPerformed(evt);
            }
        });
        search.add(deleteCarro);

        listarCarro.setText("Listar Carro");
        listarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCarroActionPerformed(evt);
            }
        });
        search.add(listarCarro);

        jMenuSearchCarro.setText("SearchCarro");
        jMenuSearchCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSearchCarroActionPerformed(evt);
            }
        });
        search.add(jMenuSearchCarro);

        jMenuBar1.add(search);

        jMenu1.setText("Bus");

        addBus.setText("Add Bus");
        addBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBusActionPerformed(evt);
            }
        });
        jMenu1.add(addBus);

        updateBus.setText("Update Bus");
        updateBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBusActionPerformed(evt);
            }
        });
        jMenu1.add(updateBus);

        deleteBus.setText("Delete Bus");
        deleteBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBusActionPerformed(evt);
            }
        });
        jMenu1.add(deleteBus);

        listarBus.setText("Listar Bus");
        listarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBusActionPerformed(evt);
            }
        });
        jMenu1.add(listarBus);

        jMenuSearchBus.setText("Search Bus");
        jMenuSearchBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSearchBusActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSearchBus);

        jMenuBar1.add(jMenu1);

        jMAddpasajero.setText("Pasajero");

        jMenuItem3.setText("Add pasajero");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMAddpasajero.add(jMenuItem3);

        jMUpdpasa.setText("Update pasajero");
        jMUpdpasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMUpdpasaActionPerformed(evt);
            }
        });
        jMAddpasajero.add(jMUpdpasa);

        jMDelePasa.setText("Delete pasajero");
        jMDelePasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDelePasaActionPerformed(evt);
            }
        });
        jMAddpasajero.add(jMDelePasa);

        jMListPasajero.setText("List pasajero");
        jMListPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListPasajeroActionPerformed(evt);
            }
        });
        jMAddpasajero.add(jMListPasajero);

        jMenuBar1.add(jMAddpasajero);

        ayuda.setText("Ayuda");

        jMenuItem2.setText("Acerca de");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        ayuda.add(jMenuItem2);

        jMenuBar1.add(ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Desarrollado por Sebastian Solano, Juan David Reyes y Julio Suarez");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void updateCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCarroActionPerformed
        // TODO add your handling code here:
        GUIUpdateCarro updateCarroFrame = new GUIUpdateCarro();
        updateCarroFrame.setLocationRelativeTo(this); // centrar respecto al principal
        updateCarroFrame.setVisible(true);
    }//GEN-LAST:event_updateCarroActionPerformed

    private void listarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCarroActionPerformed
        // TODO add your handling code here:
        GUIListCarro listCarroFrame = new GUIListCarro();
        listCarroFrame.setLocationRelativeTo(this); // centrar respecto al principal
        listCarroFrame.setVisible(true);
        barbosa.addWindow(listCarroFrame);
    }//GEN-LAST:event_listarCarroActionPerformed

    private void updateBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBusActionPerformed
        // TODO add your handling code here:

        GUIUpdateBus updateBusFrame = new GUIUpdateBus();
        updateBusFrame.setLocationRelativeTo(this); // centrar respecto al principal
        updateBusFrame.setVisible(true);

    }//GEN-LAST:event_updateBusActionPerformed

    private void deleteBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBusActionPerformed
        // TODO add your handling code here:
        GUIDeleteBus deleteBusFrame = new GUIDeleteBus();
        deleteBusFrame.setLocationRelativeTo(this); // centrar respecto al principal
        deleteBusFrame.setVisible(true);
    }//GEN-LAST:event_deleteBusActionPerformed

    private void listarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBusActionPerformed
        // TODO add your handling code here:
        GUIListBus listBusFrame = new GUIListBus();
        listBusFrame.setLocationRelativeTo(this); // centrar respecto al principal
        listBusFrame.setVisible(true);
        barbosa.addWindow(listBusFrame);
    }//GEN-LAST:event_listarBusActionPerformed

    private void addCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarroActionPerformed
        // TODO add your handling code here:

        GUIAddCarro panel = new GUIAddCarro(); // tu JPanel

        JFrame frame = new JFrame("Agregar Carro");
        frame.setContentPane(panel);
        frame.pack();
        frame.setLocationRelativeTo(null); // centrar
        frame.setVisible(true);

    }//GEN-LAST:event_addCarroActionPerformed

    private void addBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBusActionPerformed
        // TODO add your handling code here:

        GUIAddBus panel = new GUIAddBus(); // tu JPanel

        JFrame frame = new JFrame("Agregar Bus");
        frame.setContentPane(panel);
        frame.pack();
        frame.setLocationRelativeTo(null); // centrar
        frame.setVisible(true);

    }//GEN-LAST:event_addBusActionPerformed

    private void deleteCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCarroActionPerformed
        // TODO add your handling code here:
        GUIDeleteCarro deleteCarroFrame = new GUIDeleteCarro();
        deleteCarroFrame.setLocationRelativeTo(this); // centrar respecto al principal
        deleteCarroFrame.setVisible(true);
    }//GEN-LAST:event_deleteCarroActionPerformed

    private void jMenuSearchCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSearchCarroActionPerformed
        // TODO add your handling code here:
        GUISearchCarro searchCarroFrame = new GUISearchCarro();
        searchCarroFrame.setLocationRelativeTo(this); // centrar respecto al principal
        searchCarroFrame.setVisible(true);
    }//GEN-LAST:event_jMenuSearchCarroActionPerformed

    private void jMenuSearchBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSearchBusActionPerformed
        // TODO add your handling code here:
        GUISearchBus searchBusFrame = new GUISearchBus();
        searchBusFrame.setLocationRelativeTo(this); // centrar respecto al principal
        searchBusFrame.setVisible(true);
    }//GEN-LAST:event_jMenuSearchBusActionPerformed

    private void mostrarTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTarifaActionPerformed
        // TODO add your handling code here:
        GUIMostrarTarifa searchBusFrame = new GUIMostrarTarifa();
        searchBusFrame.setLocationRelativeTo(this); // centrar respecto al principal
        searchBusFrame.setVisible(true);
    }//GEN-LAST:event_mostrarTarifaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        GUIAddPasaje addPasajeroFrame = new GUIAddPasaje();
        JFrame frame = new JFrame("Agregar Pasajero");
        frame.setContentPane(addPasajeroFrame);
        frame.pack();
        frame.setLocationRelativeTo(null); // centrar
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMUpdpasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMUpdpasaActionPerformed
        // TODO add your handling code here:
        GUIUpdatePasaje addPasajeroFrame = new GUIUpdatePasaje();
        JFrame frame = new JFrame("Actualizar Pasajero");
        frame.setContentPane(addPasajeroFrame);
        frame.pack();
        frame.setLocationRelativeTo(null); // centrar
        frame.setVisible(true);
    }//GEN-LAST:event_jMUpdpasaActionPerformed

    private void jMDelePasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDelePasaActionPerformed
        // TODO add your handling code here:
        GUIDeletePasaje addPasajeroFrame = new GUIDeletePasaje();
        JFrame frame = new JFrame("Eliminar Pasajero");
        frame.setContentPane(addPasajeroFrame);
        frame.pack();
        frame.setLocationRelativeTo(null); // centrar
        frame.setVisible(true);
    }//GEN-LAST:event_jMDelePasaActionPerformed

    private void jMListPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListPasajeroActionPerformed
        // TODO add your handling code here:
        GUIListPasaje addPasajeroFrame = new GUIListPasaje(null);
        JFrame frame = new JFrame("Listar Pasajeros");
        frame.setContentPane(addPasajeroFrame);
        frame.pack();
        frame.setLocationRelativeTo(null); // centrar
        frame.setVisible(true);
    }//GEN-LAST:event_jMListPasajeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBus;
    private javax.swing.JMenuItem addCarro;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenu ayuda;
    private javax.swing.JMenuItem deleteBus;
    private javax.swing.JMenuItem deleteCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMAddpasajero;
    private javax.swing.JMenuItem jMDelePasa;
    private javax.swing.JMenuItem jMListPasajero;
    private javax.swing.JMenuItem jMUpdpasa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuSearchBus;
    private javax.swing.JMenuItem jMenuSearchCarro;
    private javax.swing.JMenuItem listarBus;
    private javax.swing.JMenuItem listarCarro;
    private javax.swing.JMenuItem mostrarTarifa;
    private javax.swing.JMenu search;
    private javax.swing.JMenuItem updateBus;
    private javax.swing.JMenuItem updateCarro;
    // End of variables declaration//GEN-END:variables
}
